server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /polls {
        proxy_pass http://poll:5000;
    }

    location /vote {
        proxy_pass http://vote:5001;
    }

    location /stats/ {
        proxy_pass http://stats:5002;
    }
}
